#include "wled.h"

#if defined(WLED_ENABLE_C3_SHARED_RGBW) && defined(CONFIG_IDF_TARGET_ESP32C3)
#include "c3_shared_rgbw.h"
#include <internal/NeoUtil.h>
#include <internal/methods/NeoEsp32RmtMethod.h>

// AI: below section was generated by an AI
C3SharedRgbwMethod* C3SharedRgbwMethod::_buses[MAX_BUSES] = {};
bool C3SharedRgbwMethod::_installed = false;
bool C3SharedRgbwMethod::_faulted = false;
bool C3SharedRgbwMethod::_busy = false;
uint8_t C3SharedRgbwMethod::_routedPin = 255;
uint32_t C3SharedRgbwMethod::_frames = 0;
uint32_t C3SharedRgbwMethod::_transfers = 0;
uint32_t C3SharedRgbwMethod::_errors = 0;
uint32_t C3SharedRgbwMethod::_frameStart = 0;
uint32_t C3SharedRgbwMethod::_lastFrameUs = 0;
uint32_t C3SharedRgbwMethod::_maxFrameUs = 0;
esp_err_t C3SharedRgbwMethod::_lastError = ESP_OK;

// Validate buffers before NeoPixelBus can access them; pin ownership belongs to BusDigital.
C3SharedRgbwMethod::C3SharedRgbwMethod(uint8_t pin, uint16_t count, size_t elementSize, size_t settingsSize, NeoBusChannel)
: _pin(pin), _size(size_t(count) * elementSize + settingsSize) {
  if (_faulted || !count || elementSize != 4 || settingsSize != 0) return;
  for (auto* bus : _buses) if (bus && bus->_pin == pin) return;
  for (auto& bus : _buses) {
    if (bus) continue;
    _editing = static_cast<uint8_t*>(d_malloc(_size));
    _sending = static_cast<uint8_t*>(d_malloc(_size));
    if (!_editing || !_sending) {
      free(_editing);
      free(_sending);
      _editing = _sending = nullptr;
      _lastError = ESP_ERR_NO_MEM;
      ++_errors;
      return;
    }
    memset(_editing, 0, _size);
    memset(_sending, 0, _size);
    bus = this;
    _registered = true;
    Initialize();
    return;
  }
}

// Restore ordinary GPIO output LOW; rmt_set_gpio alone does not disconnect an old pin.
void C3SharedRgbwMethod::detach(uint8_t pin) {
  if (pin == 255) return;
  gpio_set_level(static_cast<gpio_num_t>(pin), 0);
  gpio_matrix_out(pin, SIG_GPIO_OUT_IDX, false, false);
  gpio_set_direction(static_cast<gpio_num_t>(pin), GPIO_MODE_OUTPUT);
}

// Latch failures until reboot, stop the SDK worker and release all data lines.
// Never abort/panic on driver errors: the HTTP updater must remain usable.
void C3SharedRgbwMethod::fail(esp_err_t error) {
  _lastError = error;
  ++_errors;
  _faulted = true;
  if (_installed) {
    rmt_tx_stop(RMT_CHANNEL_0);
    if (rmt_driver_uninstall(RMT_CHANNEL_0) == ESP_OK) _installed = false;
  }
  for (auto* bus : _buses) if (bus) detach(bus->_pin);
  _routedPin = 255;
  _busy = false;
}

// One SDK driver/translator owns channel 0 for the lifetime of all logical buses.
void C3SharedRgbwMethod::Initialize() {
  if (!_registered || _faulted) return;
  detach(_pin);
  if (_installed) return;
  rmt_config_t config = {};
  config.rmt_mode = RMT_MODE_TX;
  config.channel = RMT_CHANNEL_0;
  config.gpio_num = static_cast<gpio_num_t>(_pin);
  config.clk_div = NeoEsp32RmtSpeedSk6812::RmtClockDivider;
  config.mem_block_num = 1;
  config.tx_config.idle_output_en = true;
  config.tx_config.idle_level = RMT_IDLE_LEVEL_LOW;
  config.tx_config.carrier_level = RMT_CARRIER_LEVEL_LOW;
  esp_err_t error = rmt_config(&config);
  if (error != ESP_OK) { fail(error); return; }
  error = rmt_driver_install(RMT_CHANNEL_0, 0, NEOPIXELBUS_RMT_INT_FLAGS);
  if (error != ESP_OK) { fail(error); return; }
  _installed = true;
  error = rmt_translator_init(RMT_CHANNEL_0, NeoEsp32RmtSpeedSk6812::Translate);
  if (error != ESP_OK) { fail(error); return; }
  detach(_pin);
}

// Preserve editing/readback bytes regardless of NeoPixelBus's consistency hint.
// SDK waits block only this task and allow Wi-Fi tasks to run. The timeout scales
// with nominal 10 us/byte plus 20 ms scheduling margin; it is never unbounded.
void C3SharedRgbwMethod::Update(bool) {
  if (!_registered || !_installed || _faulted || _busy) return;
  if (!_snapshot) memcpy(_sending, _editing, _size);
  _snapshot = false;
  _busy = true;
  detach(_routedPin);
  esp_err_t error = rmt_set_gpio(RMT_CHANNEL_0, RMT_MODE_TX, static_cast<gpio_num_t>(_pin), false);
  if (error == ESP_OK) {
    _routedPin = _pin;
    error = rmt_write_sample(RMT_CHANNEL_0, _sending, _size, false);
  }
  if (error == ESP_OK) {
    const uint32_t timeoutMs = (_size * 10 + 80 + 999) / 1000 + 20;
    error = rmt_wait_tx_done(RMT_CHANNEL_0, pdMS_TO_TICKS(timeoutMs) + 1);
  }
  if (error != ESP_OK) { fail(error); return; }
  // Explicit minimum latch time also protects changes in translator reset handling.
  delayMicroseconds(80);
  detach(_pin);
  _routedPin = 255;
  _busy = false;
  ++_transfers;
}

// Seal all RGBW buffers before BusManager visits the individual buses.
void C3SharedRgbwMethod::beginFrame() {
  _frameStart = micros();
  for (auto* bus : _buses) {
    if (!bus || _faulted) continue;
    memcpy(bus->_sending, bus->_editing, bus->_size);
    bus->_snapshot = true;
  }
}

// Release unused snapshots (NeoPixelBus may skip unchanged strips) and record timing.
void C3SharedRgbwMethod::endFrame() {
  for (auto* bus : _buses) if (bus) bus->_snapshot = false;
  _lastFrameUs = micros() - _frameStart;
  _maxFrameUs = std::max(_maxFrameUs, _lastFrameUs);
  ++_frames;
}

// Allows the wrapper to reject allocation/initialization failure before Begin/paint.
bool C3SharedRgbwMethod::validPin(uint8_t pin) {
  if (!_installed || _faulted) return false;
  for (auto* bus : _buses) if (bus && bus->_pin == pin) return true;
  return false;
}

// Configuration changes occur outside synchronous transfers; unregister before free.
C3SharedRgbwMethod::~C3SharedRgbwMethod() {
  if (_registered) {
    detach(_pin);
    for (auto& bus : _buses) if (bus == this) bus = nullptr;
    bool any = false;
    for (auto* bus : _buses) any |= bus != nullptr;
    if (!any && _installed) {
      esp_err_t error = rmt_driver_uninstall(RMT_CHANNEL_0);
      if (error == ESP_OK) _installed = false;
      else fail(error);
    }
  }
  free(_editing);
  // If even driver shutdown failed, retain the ISR-visible snapshot rather than
  // risking use-after-free. A latched fault prevents further allocation until reboot.
  if (!_faulted || !_installed) free(_sending);
}

// Snapshot primitive counters for read-only Wi-Fi diagnostics.
C3SharedRgbwMethod::Diagnostics C3SharedRgbwMethod::diagnostics() {
  uint8_t count = 0;
  for (auto* bus : _buses) if (bus) ++count;
  return {count, _installed && !_faulted, _faulted, _frames, _transfers, _errors,
          _lastFrameUs, _maxFrameUs, static_cast<int>(_lastError)};
}
// AI: end
#endif
