#pragma once

#if defined(WLED_ENABLE_C3_SHARED_RGBW) && defined(CONFIG_IDF_TARGET_ESP32C3)
#include <Arduino.h>
#include <internal/NeoSettings.h>
#include <internal/NeoBusChannel.h>

// AI: below section was generated by an AI
// NeoPixelBus byte-buffer method for four logical RGBW strips sharing one C3 TX channel.
// Protocol encoding remains NeoPixelBus's pinned SK6812 translator; WLED owns color processing.
// Sources: Makuna/NeoPixelBus NeoEsp32RmtMethod.h and ESP-IDF v4.4.8 driver/rmt.h.
class C3SharedRgbwMethod {
public:
  typedef NeoNoSettings SettingsObject;
  static constexpr uint8_t MAX_BUSES = 4;

  C3SharedRgbwMethod(uint8_t pin, uint16_t count, size_t elementSize, size_t settingsSize, NeoBusChannel channel);
  ~C3SharedRgbwMethod();
  C3SharedRgbwMethod(const C3SharedRgbwMethod&) = delete;
  C3SharedRgbwMethod& operator=(const C3SharedRgbwMethod&) = delete;

  void Initialize();
  void Update(bool maintainBufferConsistency);
  bool IsReadyToUpdate() const { return !_busy; }
  bool AlwaysUpdate() const { return false; }
  bool SwapBuffers() { return false; }
  uint8_t* getData() const { return _editing; }
  size_t getDataSize() const { return _size; }
  void applySettings(const SettingsObject&) {}

  // A frame barrier snapshots every output after WLED's ABL processing, before any sends.
  static void beginFrame();
  static void endFrame();
  static bool validPin(uint8_t pin);
  struct Diagnostics {
    uint8_t buses;
    bool ready;
    bool faulted;
    uint32_t frames, transfers, errors, frameUs, maxFrameUs;
    int lastError;
  };
  static Diagnostics diagnostics();

private:
  const uint8_t _pin;
  const size_t _size;
  uint8_t* _editing = nullptr;
  uint8_t* _sending = nullptr;
  bool _registered = false;
  bool _snapshot = false;

  static C3SharedRgbwMethod* _buses[MAX_BUSES];
  static bool _installed;
  static bool _faulted;
  static bool _busy;
  static uint8_t _routedPin;
  static uint32_t _frames;
  static uint32_t _transfers;
  static uint32_t _errors;
  static uint32_t _frameStart;
  static uint32_t _lastFrameUs;
  static uint32_t _maxFrameUs;
  static esp_err_t _lastError;

  static void detach(uint8_t pin);
  static void fail(esp_err_t error);
};
// AI: end
#endif
