#include "wled.h"
#include "spatial_canvas_math.h"

#ifdef WLED_ENABLE_SPATIAL_CANVAS
// AI: below section was generated by an AI
// Architecture: native WLED 2D segment -> composed grid -> four sampled 1D segments.
// Sources: WLED FX_fcn.cpp/FX_2Dfcn.cpp and its user_fx registration example.
namespace {
using SpatialCanvasMath::Path;
struct Look {
  uint32_t colors[3] = {0xFFA000, 0, 0};
  uint8_t fx = 9, pal = 0, speed = 64, intensity = 128, opacity = 255, cct = 127;
  uint8_t custom1 = 128, custom2 = 128, custom3 = 16;
  uint16_t options = SEGMENT_ON, offset = 0;
  uint8_t grouping = 1, spacing = 0;
  char name[33] = {};
};
struct CanvasConfig {
  bool enabled = false;
  uint8_t width = 32, height = 20;
  Path paths[4] = {
    {{.14f,.12f},{.86f,.12f}}, {{.10f,.85f},{.90f,.85f}},
    {{.29f,.26f},{.29f,.67f}}, {{.71f,.26f},{.71f,.67f}}
  };
  Look normal[4];
};
CanvasConfig canvas;
StaticJsonDocument<6144> pendingDocument;
bool pending = false, processing = false;
uint8_t sliceEffect = 0, canvasError = 0;
const char *defaultNames[4] = {"Light bar", "Desk", "Left monitor", "Right monitor"};

// Sampling occurs after composition. With canvas off this effect falls back to Solid.
void sliceMode() {
  Segment &seg = *strip._currentSegment;
  seg.fill(canvas.enabled ? BLACK : seg.colors[0]);
}

// Only coherent one-wire outputs participate. No GPIO or bus configuration is changed.
bool supported() {
  if (BusManager::getNumBusses() != 4 || strip.getLengthPhysical() > 1024) return false;
  unsigned end = 0;
  for (unsigned i = 0; i < 4; i++) {
    const Bus *bus = BusManager::getBus(i);
    if (!bus || !bus->isOk() || bus->getType() != TYPE_SK6812_RGBW || bus->getStart() != end) return false;
    end += bus->getLength();
  }
  return end > 0;
}

// Paths bind to reported GPIOs rather than trusting client-supplied offsets or lengths.
int busForPin(unsigned pin) {
  for (unsigned i = 0; i < BusManager::getNumBusses() && i < 4; i++) {
    uint8_t pins[5] = {};
    const Bus *bus = BusManager::getBus(i);
    if (bus && bus->getPins(pins) == 1 && pins[0] == pin) return i;
  }
  return -1;
}

bool readPoint(JsonVariant value, SpatialCanvasMath::Point &point) {
  JsonArray coordinates = value.as<JsonArray>();
  if (coordinates.size() != 2 || !coordinates[0].is<float>() || !coordinates[1].is<float>()) return false;
  point = {coordinates[0].as<float>(), coordinates[1].as<float>()};
  return SpatialCanvasMath::valid(point);
}

// Validate the entire edit before publishing any changes.
bool parseConfig(JsonObject object, CanvasConfig &candidate, bool fromFS) {
  if (object.isNull()) return false;
  if (object.containsKey("enabled")) {
    if (!object["enabled"].is<bool>()) return false;
    candidate.enabled = object["enabled"].as<bool>();
  }
  unsigned width = object["width"] | candidate.width, height = object["height"] | candidate.height;
  if (width < 16 || width > 64 || height < 10 || height > 40 || width * 5 != height * 8) return false;
  candidate.width = width; candidate.height = height;
  if (object.containsKey("strips")) {
    JsonArray paths = object["strips"].as<JsonArray>();
    if (paths.isNull() || paths.size() != 4) return false;
    unsigned seen = 0, index = 0;
    for (JsonObject path : paths) {
      int bus = fromFS ? int(index++) : busForPin(path["pin"] | 255U);
      if (bus < 0 || bus >= 4 || (seen & (1U << bus))) return false;
      seen |= 1U << bus;
      if (!readPoint(path["a"], candidate.paths[bus].a) || !readPoint(path["b"], candidate.paths[bus].b)) return false;
      if (!path["reverse"].is<bool>()) return false;
      candidate.paths[bus].reverse = path["reverse"].as<bool>();
    }
  }
  return true;
}

void capture(Look &look, const Segment &seg) {
  for (unsigned j = 0; j < 3; j++) look.colors[j] = seg.colors[j];
  look.fx = seg.mode; look.pal = seg.palette; look.speed = seg.speed; look.intensity = seg.intensity;
  look.opacity = seg.opacity; look.cct = seg.cct; look.options = seg.options;
  look.custom1 = seg.custom1; look.custom2 = seg.custom2; look.custom3 = seg.custom3;
  look.grouping = seg.grouping; look.spacing = seg.spacing; look.offset = seg.offset;
  if (seg.name) strlcpy(look.name, seg.name, sizeof(look.name));
}

void apply(const Look &look, Segment &seg) {
  seg.setMode(look.fx); seg.palette = look.pal; seg.speed = look.speed; seg.intensity = look.intensity;
  for (unsigned j = 0; j < 3; j++) seg.colors[j] = look.colors[j];
  seg.opacity = look.opacity; seg.cct = look.cct; seg.options = look.options;
  seg.custom1 = look.custom1; seg.custom2 = look.custom2; seg.custom3 = look.custom3;
  seg.grouping = look.grouping; seg.spacing = look.spacing; seg.offset = look.offset;
  seg.setName(look.name);
}

void writeLook(JsonObject object, const Look &look) {
  object["n"] = look.name; object["fx"] = look.fx; object["pal"] = look.pal;
  object["sx"] = look.speed; object["ix"] = look.intensity; object["bri"] = look.opacity;
  object["cct"] = look.cct; object["options"] = look.options;
  object["c1"] = look.custom1; object["c2"] = look.custom2; object["c3"] = look.custom3;
  object["grp"] = look.grouping; object["spc"] = look.spacing; object["of"] = look.offset;
  JsonArray colors = object.createNestedArray("colors");
  for (uint32_t color : look.colors) colors.add(color);
}

void readLook(JsonObject object, Look &look) {
  strlcpy(look.name, object["n"] | "", sizeof(look.name));
  look.fx = object["fx"] | 9; look.pal = object["pal"] | 0;
  look.speed = object["sx"] | 64; look.intensity = object["ix"] | 128;
  look.opacity = object["bri"] | 255; look.cct = object["cct"] | 127;
  look.options = object["options"] | SEGMENT_ON;
  look.custom1 = object["c1"] | 128; look.custom2 = object["c2"] | 128; look.custom3 = object["c3"] | 16;
  look.grouping = max(1, object["grp"] | 1); look.spacing = object["spc"] | 0; look.offset = object["of"] | 0;
  for (unsigned j = 0; j < 3; j++) look.colors[j] = object["colors"][j] | look.colors[j];
}

// A bounded queued replay preserves ordinary preset/state fields across topology changes.
bool legacyBounds(JsonObject root) {
  if (!canvas.enabled || root.containsKey("canvas")) return false;
  JsonArray segments = root["seg"].as<JsonArray>();
  for (JsonObject segment : segments) {
    if (!segment.containsKey("start") || !segment.containsKey("stop")) continue;
    unsigned start = segment["start"] | 65535U, stop = segment["stop"] | 65535U;
    for (unsigned i = 0; i < 4; i++) {
      const Bus *bus = BusManager::getBus(i);
      if (bus && start == bus->getStart() && stop == start + bus->getLength()) return true;
    }
  }
  return false;
}
}

bool spatialCanvasEnabled() { return canvas.enabled; }
uint16_t spatialCanvasOffset() { return unsigned(canvas.width) * canvas.height; }
// Virtual pixels advertise RGBW capability, but show() never paints them on a bus.
uint16_t spatialCanvasMap(uint16_t index) {
  unsigned offset = spatialCanvasOffset();
  return index < offset ? 0 : index - offset;
}

bool spatialCanvasQueue(JsonObject root, uint8_t presetId) {
  // Preserve a legacy startup-off preset without replacing the new canvas geometry.
  if (presetId && presetId == bootPreset && !(root["on"] | true) && legacyBounds(root)) {
    root.remove("seg");
    return false;
  }
  if (processing || (!root.containsKey("canvas") && !legacyBounds(root))) return false;
  if (pending) { canvasError = 4; return true; }
  CanvasConfig candidate = canvas;
  if (root.containsKey("canvas") && !parseConfig(root["canvas"].as<JsonObject>(), candidate, false)) {
    canvasError = 1; return true;
  }
  pendingDocument.clear();
  if (!pendingDocument.set(root) || pendingDocument.overflowed()) { canvasError = 1; pendingDocument.clear(); return true; }
  if (!root.containsKey("canvas")) pendingDocument["canvas"]["enabled"] = false;
  pending = true; canvasError = 0;
  return true;
}

void spatialCanvasPrepareMatrix() {
  if (!canvas.enabled) return;
  if (!supported()) {
    canvas.enabled = false; canvasError = 3;
    strip.isMatrix = false; strip.panel.clear();
    Segment::maxWidth = strip.getLengthPhysical(); Segment::maxHeight = 1;
    return;
  }
  strip.isMatrix = true;
  Segment::maxWidth = canvas.width; Segment::maxHeight = canvas.height;
  strip.panel.clear();
  WS2812FX::Panel panel;
  panel.width = canvas.width; panel.height = canvas.height;
  strip.panel.push_back(panel);
}

// Called at boot and from the main loop, never while effects are being serviced.
void spatialCanvasRegisterEffect() {
  if (!sliceEffect) sliceEffect = strip.addEffect(255, &sliceMode, PSTR("Canvas Slice@;;!;1"));
}

void spatialCanvasSegments() {
  spatialCanvasRegisterEffect();
  strip.resetSegments();
  Segment &scene = strip.getSegment(0);
  scene.setName("Scene"); scene.setMode(FX_MODE_2DPLASMAROTOZOOM, true);
  for (unsigned i = 0; i < 4 && i < BusManager::getNumBusses(); i++) {
    const Bus *bus = BusManager::getBus(i);
    unsigned start = spatialCanvasOffset() + bus->getStart();
    strip.appendSegment(start, start + bus->getLength());
    Segment &seg = strip.getSegment(i + 1);
    seg.setName(canvas.normal[i].name[0] ? canvas.normal[i].name : defaultNames[i]);
    seg.setMode(sliceEffect);
    seg.selected = false;
    seg.on = true;
  }
  // Constructors start with empty capabilities; publish RGBW controls immediately.
  for (unsigned i = 0; i < strip.getSegmentsNum(); i++) strip.getSegment(i).refreshLightCapabilities();
  strip.setMainSegmentId(0);
}

void spatialCanvasLoop() {
  if (!pending || !requestJSONBufferLock(JSON_LOCK_CFG_DES)) return;
  JsonObject root = pendingDocument.as<JsonObject>();
  CanvasConfig candidate = canvas;
  bool valid = parseConfig(root["canvas"].as<JsonObject>(), candidate, false);
  if (!valid || (candidate.enabled && !supported())) canvasError = valid ? 3 : 1;
  else {
    bool changed = candidate.enabled != canvas.enabled || candidate.width != canvas.width || candidate.height != canvas.height;
    // Geometry rebuilds are bounded, and only allocate on explicit edits.
    if (changed) {
      strip.suspend();
      if (strip.isServicing()) canvasError = 4;
      else if (!strip.tryPixelBuffer((candidate.enabled ? unsigned(candidate.width) * candidate.height : 0) + strip.getLengthPhysical())) canvasError = 2;
      else {
        if (!canvas.enabled && candidate.enabled) {
          for (unsigned i = 0; i < 4; i++) {
            const Bus *bus = BusManager::getBus(i);
            for (unsigned s = 0; s < strip.getSegmentsNum(); s++) {
              const Segment &seg = strip.getSegment(s);
              if (seg.start == bus->getStart() && seg.stop == bus->getStart() + bus->getLength()) capture(candidate.normal[i], seg);
            }
          }
        }
        Look sceneLook, currentLooks[4];
        bool wasEnabled = canvas.enabled;
        if (wasEnabled) {
          capture(sceneLook, strip.getSegment(0));
          for (unsigned i = 0; i < 4; i++) {
            capture(currentLooks[i], strip.getSegment(i + 1));
            if (!candidate.enabled) {
              if (currentLooks[i].fx != sliceEffect) candidate.normal[i] = currentLooks[i];
              else {
                candidate.normal[i].opacity = currentLooks[i].opacity;
                candidate.normal[i].options = currentLooks[i].options;
                strlcpy(candidate.normal[i].name, currentLooks[i].name, sizeof(candidate.normal[i].name));
              }
            }
          }
        }
        canvas = candidate;
        if (canvas.enabled) {
          spatialCanvasPrepareMatrix(); spatialCanvasSegments();
          if (wasEnabled) {
            apply(sceneLook, strip.getSegment(0));
            for (unsigned i = 0; i < 4; i++) apply(currentLooks[i], strip.getSegment(i + 1));
          }
        } else {
          strip.isMatrix = false; strip.panel.clear();
          Segment::maxWidth = strip.getLengthPhysical(); Segment::maxHeight = 1;
          strip.resetSegments();
          for (unsigned i = 0; i < 4; i++) {
            const Bus *bus = BusManager::getBus(i);
            if (i) strip.appendSegment(bus->getStart(), bus->getStart() + bus->getLength());
            Segment &seg = strip.getSegment(i);
            seg.setGeometry(bus->getStart(), bus->getStart() + bus->getLength());
            apply(canvas.normal[i], seg);
            seg.refreshLightCapabilities();
          }
        }
      }
      strip.resume();
    } else canvas = candidate;
    if (!canvasError) {
      processing = true;
      deserializeState(root);
      processing = false;
      configNeedsWrite = true;
      strip.trigger();
      interfaceUpdateCallMode = CALL_MODE_WS_SEND;
    }
  }
  pending = false;
  pendingDocument.clear();
  releaseJSONBufferLock();
}

void spatialCanvasReadConfig(JsonObject root) {
  JsonObject object = root["canvas"];
  if (object.isNull()) return;
  CanvasConfig candidate = canvas;
  if (!parseConfig(object, candidate, true)) { canvasError = 1; return; }
  JsonArray normal = object["normal"];
  if (normal.size() == 4) for (unsigned i = 0; i < 4; i++) readLook(normal[i], candidate.normal[i]);
  canvas = candidate;
}

// Discovery advertises physical count separately from WLED's virtual pixel count.
void spatialCanvasWriteInfo(JsonObject root) {
  JsonObject object = root.createNestedObject("canvas");
  object["version"] = 1;
  object["enabled"] = canvas.enabled;
  object["physicalCount"] = strip.getLengthPhysical();
}

void spatialCanvasWriteState(JsonObject root) {
  JsonObject object = root.createNestedObject("canvas");
  object["enabled"] = canvas.enabled;
  object["width"] = canvas.width; object["height"] = canvas.height;
  object["offset"] = canvas.enabled ? spatialCanvasOffset() : 0;
  object["scene"] = 0; object["sliceFx"] = sliceEffect;
  object["physicalCount"] = strip.getLengthPhysical();
  object["pending"] = pending; object["error"] = canvasError;
  JsonArray paths = object.createNestedArray("strips");
  for (unsigned i = 0; i < 4 && i < BusManager::getNumBusses(); i++) {
    const Bus *bus = BusManager::getBus(i);
    uint8_t pins[5] = {};
    bus->getPins(pins);
    JsonObject path = paths.createNestedObject();
    path["pin"] = pins[0]; path["start"] = bus->getStart(); path["len"] = bus->getLength();
    path["segment"] = canvas.enabled ? i + 1 : i;
    const Segment &seg = strip.getSegment(canvas.enabled ? i + 1 : i);
    path["name"] = seg.name ? seg.name : (canvas.normal[i].name[0] ? canvas.normal[i].name : defaultNames[i]);
    JsonArray a = path.createNestedArray("a"), b = path.createNestedArray("b");
    a.add(canvas.paths[i].a.x); a.add(canvas.paths[i].a.y);
    b.add(canvas.paths[i].b.x); b.add(canvas.paths[i].b.y);
    path["reverse"] = canvas.paths[i].reverse;
  }
}

void spatialCanvasWriteConfig(JsonObject root) {
  spatialCanvasWriteState(root);
  JsonArray normal = root["canvas"].createNestedArray("normal");
  for (const Look &look : canvas.normal) writeLook(normal.createNestedObject(), look);
}

// Sample after scene composition; each physical strip remains an ordinary WLED segment.
void spatialCanvasSample() {
  if (!canvas.enabled || !supported()) return;
  unsigned offset = spatialCanvasOffset();
  for (unsigned busIndex = 0; busIndex < 4; busIndex++) {
    const Bus *bus = BusManager::getBus(busIndex);
    unsigned start = offset + bus->getStart();
    for (unsigned s = 1; s < strip.getSegmentsNum(); s++) {
      const Segment &seg = strip.getSegment(s);
      if (seg.start != start || seg.stop != start + bus->getLength() || seg.mode != sliceEffect) continue;
      unsigned brightness = seg.currentBri();
      for (unsigned i = 0; i < bus->getLength(); i++) {
        auto point = SpatialCanvasMath::point(canvas.paths[busIndex], i, bus->getLength());
        uint32_t color = SpatialCanvasMath::sample(point, canvas.width, canvas.height, [](unsigned index) { return strip.getPixelColorNoMap(index); });
        uint32_t dimmed = 0;
        for (unsigned shift = 0; shift < 32; shift += 8) dimmed |= ((((color >> shift) & 255) * brightness + 127) / 255) << shift;
        strip.setPixelColor(start + i, dimmed);
      }
    }
  }
}
// Bounded readback for qualification: at most 64 scene or physical pixels per request.
// Taking the JSON lock prevents a concurrent canvas geometry edit during the read.
void spatialCanvasServePixels(AsyncWebServerRequest *request) {
  bool scene = request->hasParam("scene");
  int from = request->hasParam("from") ? request->getParam("from")->value().toInt() : 0;
  int count = request->hasParam("count") ? request->getParam("count")->value().toInt() : 64;
  unsigned length = scene && canvas.enabled ? spatialCanvasOffset() : strip.getLengthPhysical();
  if (from < 0 || unsigned(from) >= length || count < 1 || count > 64 || (scene && !canvas.enabled)) {
    request->send(400, CONTENT_TYPE_JSON, F("{\"error\":\"range\"}")); return;
  }
  if (strip.isServicing()) { request->send(503, CONTENT_TYPE_JSON, F("{\"error\":\"busy\"}")); return; }
  if (!requestJSONBufferLock(JSON_LOCK_SERVEJSON)) { request->deferResponse(); return; }
  uint32_t frame = strip.getLastShow();
  count = min(unsigned(count), length - unsigned(from));
  AsyncJsonResponse *response = new AsyncJsonResponse(JSON_ARRAY_SIZE(128) + JSON_OBJECT_SIZE(6), false);
  JsonObject root = response->getRoot();
  root["from"] = from; root["count"] = count; root["frame"] = frame;
  JsonArray values = root.createNestedArray("pixels");
  JsonArray composed = root.createNestedArray("composed");
  for (int i = from; i < from + count; i++) {
    if (scene) values.add(strip.getPixelColorNoMap(i));
    else {
      values.add(BusManager::getPixelColor(i));
      unsigned logical = canvas.enabled && (realtimeMode == REALTIME_MODE_INACTIVE || realtimeRespectLedMaps) ? spatialCanvasOffset() + i : i;
      composed.add(strip.getPixelColorNoMap(logical));
    }
  }
  // Discard a read overlapping composition rather than exposing a partial frame.
  if (strip.isServicing() || frame != strip.getLastShow()) {
    delete response;
    releaseJSONBufferLock();
    request->send(503, CONTENT_TYPE_JSON, F("{\"error\":\"busy\"}")); return;
  }
  response->setLength();
  releaseJSONBufferLock();
  request->send(response);
}
// AI: end
#endif
