#pragma once
#include <cmath>
#include <cstdint>

// AI: below section was generated by an AI
// Continuous paths avoid the one-LED-per-cell restriction of a sparse ledmap.
namespace SpatialCanvasMath {
struct Point { float x, y; };
struct Path {
  Point a, b; bool reverse;
  Path(Point first = {0, 0}, Point last = {1, 1}, bool reversed = false) : a(first), b(last), reverse(reversed) {}
};

inline bool valid(Point p) {
  return std::isfinite(p.x) && std::isfinite(p.y) && p.x >= 0 && p.x <= 1 && p.y >= 0 && p.y <= 1;
}

inline Point point(const Path &path, unsigned pixel, unsigned length) {
  float t = length > 1 ? float(pixel) / float(length - 1) : 0.5f;
  if (path.reverse) t = 1.0f - t;
  return {path.a.x + t * (path.b.x - path.a.x), path.a.y + t * (path.b.y - path.a.y)};
}

// Bilinear sampling preserves RGBW and permits any number of LEDs per cell.
template <typename Read>
uint32_t sample(Point p, unsigned width, unsigned height, Read read) {
  if (!width || !height || !valid(p)) return 0;
  float x = p.x * (width - 1), y = p.y * (height - 1);
  unsigned x0 = unsigned(x), y0 = unsigned(y);
  unsigned x1 = x0 + (x0 + 1 < width), y1 = y0 + (y0 + 1 < height);
  float dx = x - x0, dy = y - y0;
  uint32_t colors[4] = {read(x0 + y0 * width), read(x1 + y0 * width), read(x0 + y1 * width), read(x1 + y1 * width)};
  uint32_t result = 0;
  for (unsigned shift = 0; shift < 32; shift += 8) {
    float top = ((colors[0] >> shift) & 255) * (1-dx) + ((colors[1] >> shift) & 255) * dx;
    float bottom = ((colors[2] >> shift) & 255) * (1-dx) + ((colors[3] >> shift) & 255) * dx;
    result |= uint32_t(top * (1-dy) + bottom * dy + 0.5f) << shift;
  }
  return result;
}
}
// AI: end
