#pragma once

// AI: below section was generated by an AI
// The grid is virtual. Only the original physical buses are sent to the driver.
#ifdef WLED_ENABLE_SPATIAL_CANVAS
bool spatialCanvasEnabled();
uint16_t spatialCanvasOffset();
uint16_t spatialCanvasMap(uint16_t index);
bool spatialCanvasQueue(JsonObject root, uint8_t presetId = 0);
void spatialCanvasLoop();
void spatialCanvasRegisterEffect();
void spatialCanvasReadConfig(JsonObject root);
void spatialCanvasWriteConfig(JsonObject root);
void spatialCanvasWriteState(JsonObject root);
void spatialCanvasWriteInfo(JsonObject root);
void spatialCanvasPrepareMatrix();
void spatialCanvasSegments();
void spatialCanvasSample();
void spatialCanvasServePixels(AsyncWebServerRequest *request);
#endif
// AI: end
