// AI: below section was generated by an AI.
// Mount only in the local review server, preserving the prototype's keyboard controls.
import React from 'react';
import { createRoot } from 'react-dom/client';
import { Agentation } from 'agentation';

const host = document.createElement('div');
host.id = 'wled-review-toolbar';
document.body.append(host);
createRoot(host).render(<Agentation
	appName="WLED Canvas local prototype"
	endpoint="http://localhost:4747"
	enableKeyboardShortcuts={false}
	onSessionCreated={id => { window.wledAgentationSessionId = id; }}
	onAnnotationAdd={annotation => { window.wledLastAnnotation = annotation; }}
/>);
// AI: end
