#!/usr/bin/env python3
"""Build offline reference thumbnails and palette stops for the Canvas prototype.

Requires Pillow in a development environment. No controller requests are made.
WLED's documentation links these animations, captured by WLED-Utils. They use
reference colors/Party, not the current prototype's palette or slider settings.
"""
# AI: below section was generated by an AI.
import base64
import concurrent.futures
import hashlib
import io
import json
import re
import urllib.request
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = Path(__file__).with_name('reference-previews.json')
GALLERY = ROOT / 'tools/wled-ui-options-prototype.html'
UTILS_COMMIT = 'ec0bad83b35358137569d4cc9a016e235e00ffed'
EFFECTS = [
    ('Blends', 115), ('Ripple Rainbow', 99), ('Aurora', 38), ('Solid', 0),
    ('Fire 2012', 66), ('Fill Noise', 69), ('Pacifica', 101), ('Rainbow', 9),
    ('Akemi', 186), ('Black Hole', 183), ('Blink', 1), ('Blobs', 121),
    ('Blurz', 163), ('Bouncing Balls', 91), ('Breathe', 2), ('Chase', 28),
    ('Colorwaves', 67), ('Dancing Shadows', 112), ('Drip', 96), ('Flow', 110),
    ('Glitter', 87), ('Lake', 75), ('Meteor', 76), ('Palette', 65),
    ('Plasma', 97), ('Twinkle', 17),
]


def inline_image(image, **options):
    """Encode a reference image directly so the gallery stays self-contained."""
    buffer = io.BytesIO()
    image.save(buffer, format='WEBP', lossless=True, **options)
    return 'data:image/webp;base64,' + base64.b64encode(buffer.getvalue()).decode()


def effect_preview(item):
    """Resize complete reference frames without cropping; preserve loop timing."""
    name, effect_id = item
    metadata = re.findall(r'_data_\w+\[\]\s+PROGMEM\s*=\s*"([^"]+)"', (ROOT / 'wled00/FX.cpp').read_text())
    descriptor = next(entry for entry in metadata if entry.split('@')[0] == name)
    default_palette = re.search(r'(?:^|[;,])pal=(\d+)', descriptor)
    details = {'id': effect_id, 'name': name, 'defaultPalette': int(default_palette.group(1)) if default_palette else 0}
    if effect_id == 0:
        return {**details, 'source': 'wled00/FX.cpp: mode_static'}
    url = f'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/{UTILS_COMMIT}/gifs/FX_{effect_id:03}.gif'
    with urllib.request.urlopen(url, timeout=30) as response:
        original = response.read()
    animation = Image.open(io.BytesIO(original))
    frames, durations = [], []
    # Keep every third frame at its original elapsed time, not a sped-up loop.
    for index in range(animation.n_frames):
        animation.seek(index)
        duration = animation.info.get('duration', 100)
        if index % 3 == 0:
            frames.append(ImageOps.contain(animation.convert('RGB'), (48, 32), Image.Resampling.NEAREST))
            durations.append(duration)
        else:
            durations[-1] += duration
    return {
        **details, 'source': url,
        'sha256': hashlib.sha256(original).hexdigest(),
        'animation': inline_image(frames[0], save_all=True, append_images=frames[1:], duration=durations, loop=0),
        'still': inline_image(frames[min(4, len(frames) - 1)]),
        'frames': len(frames), 'durationMs': sum(durations),
        'width': frames[0].width, 'height': frames[0].height,
    }


def palette_previews():
    """Extract the same RGB/index data used by WLED's /json/palx response."""
    source = (ROOT / 'wled00/palettes.cpp').read_text()
    fx = (ROOT / 'wled00/FX_fcn.cpp').read_text()
    names = json.loads(re.search(r'JSON_palette_names\[\].*?R"=====\((.*?)\)====="', fx, re.S).group(1))
    colors = dict(re.findall(r'\b(\w+)\s*=\s*(0x[0-9A-Fa-f]{6})\b', (ROOT / 'wled00/src/dependencies/fastled_slim/fastled_slim.h').read_text()))

    def rgb(hex_color):
        value = int(hex_color, 16)
        return [(value >> shift) & 255 for shift in (16, 8, 0)]

    def body(symbol):
        found = re.search(r'\b' + symbol + r'(?:\[\])?\s+PROGMEM\s*=\s*\{(.*?)\}', source, re.S)
        return re.sub(r'//[^\n]*', '', found.group(1))

    fastled = re.findall(r'&(\w+)', body('fastledPalettes'))
    gradient = re.findall(r'\b(\w+)\b', body('gGradientPalettes'))
    dynamic = [None, ['r'] * 4, ['c1'], ['c1', 'c1', 'c2', 'c2'], ['c3', 'c2', 'c1'], ['c1'] * 5 + ['c2'] * 5 + ['c3'] * 5 + ['c1']]
    palettes = []
    for palette_id, name in enumerate(names):
        if palette_id < 6:
            stops = dynamic[palette_id]
        elif palette_id < 13:
            entries = re.findall(r'CRGB::(\w+)|\b(0x[\da-fA-F]+)\b', body(fastled[palette_id - 6]))
            stops = [[index << 4, *rgb(hex_color or colors[symbol])] for index, (symbol, hex_color) in enumerate(entries)]
            assert len(stops) == 16
        else:
            numbers = [int(value) for value in re.findall(r'\b\d+\b', body(gradient[palette_id - 13]))]
            assert len(numbers) % 4 == 0
            stops = [numbers[index:index + 4] for index in range(0, len(numbers), 4)]
            assert stops[0][0] == 0 and stops[-1][0] == 255
        palettes.append({'id': palette_id, 'name': name.removeprefix('* '), 'stops': stops})
    assert len(palettes) == 72
    return palettes


def embed_references(data):
    """Update only Canvas's runtime/styles and the gallery's offline data block."""
    page = GALLERY.read_text()
    match = re.search(r'const variants=(.*?);\nconst commonCss=', page, re.S)
    variants = json.loads(match.group(1))
    boot_marker = '\n// AI: below section was generated by an AI.\n// WLED-Docs'
    css_marker = '\n/* AI: below section was generated by an AI.\n   Reference previews'
    canvas = variants[1]
    canvas['boot'] = canvas['boot'].split(boot_marker)[0] + '\n' + Path(__file__).with_name('canvas-reference-previews.js').read_text()
    canvas['css'] = canvas['css'].split(css_marker)[0] + '\n' + Path(__file__).with_name('canvas-reference-previews.css').read_text()
    encoded_variants = json.dumps(variants, ensure_ascii=False).replace('</', '<\\/')
    page = page[:match.start(1)] + encoded_variants + page[match.end(1):]
    block = '// BEGIN CANVAS REFERENCE DATA\nwindow.canvasReferencePreviews=' + json.dumps(data, separators=(',', ':')).replace('</', '<\\/') + ';\n// END CANVAS REFERENCE DATA\n'
    if '// BEGIN CANVAS REFERENCE DATA' in page:
        page = re.sub(r'// BEGIN CANVAS REFERENCE DATA\n.*?// END CANVAS REFERENCE DATA\n', lambda _: block, page, flags=re.S)
    else:
        page = page.replace("const app=document.getElementById('app');", block + "const app=document.getElementById('app');", 1)
    GALLERY.write_text(page)


if __name__ == '__main__':
    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
        effects = list(pool.map(effect_preview, EFFECTS))
    result = {
        'source': 'https://kno.wled.ge/features/effects/',
        'animationCommit': UTILS_COMMIT,
        'paletteSources': ['wled00/palettes.cpp', 'wled00/FX_fcn.cpp', 'wled00/json.cpp', 'wled00/data/index.js'],
        'effects': effects, 'palettes': palette_previews(),
        'license': Path(__file__).with_name('WLED-Utils-LICENSE.txt').read_text(),
    }
    OUTPUT.write_text(json.dumps(result, separators=(',', ':')) + '\n')
    embed_references(result)
    print(f'Built {len(effects)} effect references and {len(result["palettes"])} palettes: {OUTPUT.stat().st_size} bytes')
# AI: end
