// AI: below section was generated by an AI
// Loopback-only WLED simulator. Serves the production UI and never contacts hardware.
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),data=path.join(root,'wled00/data');
const references=JSON.parse(fs.readFileSync(path.join(root,'tools/wled-ui-review/reference-previews.json'),'utf8'));
const fx=fs.readFileSync(path.join(root,'wled00/FX.cpp'),'utf8'),headers=fs.readFileSync(path.join(root,'wled00/FX.h'),'utf8');
const ids=Object.fromEntries([...headers.matchAll(/^#define\s+(FX_MODE_\w+)\s+(\d+)/gm)].map(match=>[match[1],Number(match[2])]));
const effects=[],fxdata=[];
for(const match of fx.matchAll(/static const char _data_(FX_MODE_\w+)\[\] PROGMEM = "([^"\n]*)";/g)){const id=ids[match[1]];if(id===undefined)continue;const [name,description='']=match[2].split('@');effects[id]=name;fxdata[id]=description;}
for(let id=0;id<effects.length;id++){effects[id]||=`Effect ${id}`;fxdata[id]||='';}effects.push('Canvas Slice');fxdata.push('');
const layout={enabled:true,width:32,height:20,scene:0,sliceFx:effects.length-1,physicalCount:299,pending:false,error:0,realtime:false,strips:[{name:'Light Bar',pin:2,len:119,start:0,a:[.14,.12],b:[.86,.12]},{name:'Desk',pin:3,len:118,start:119,a:[.1,.85],b:[.9,.85]},{name:'Left Monitor',pin:5,len:31,start:237,a:[.29,.26],b:[.29,.67]},{name:'Right Monitor',pin:6,len:31,start:268,a:[.71,.26],b:[.71,.67]}].map((item,index)=>({...item,segment:index+1,reverse:false}))};
function makeSegment(id,name,start,stop,fx=115){return {id,n:name,start,stop,len:stop-start,grp:1,spc:0,of:0,on:true,frz:false,bri:255,cct:127,lc:7,col:[[229,174,156,0],[0,0,0,0],[0,0,0,0]],fx,sx:128,ix:128,pal:6,c1:128,c2:128,c3:16,o1:false,o2:false,o3:false,sel:id===0,rev:false,mi:false,m12:0,si:0,bm:0};}
let state={on:true,bri:96,transition:7,ps:-1,pl:-1,mainseg:0,nl:{on:false,dur:30,mode:1,tbri:0,rem:-1},udpn:{send:false,recv:true},lor:0,canvas:layout,seg:[{...makeSegment(0,'Scene',0,32),startY:0,stopY:20},...layout.strips.map(p=>makeSegment(p.segment,p.name,640+p.start,640+p.start+p.len,layout.sliceFx))]};
let presets={'0':{},'1':{n:'Evening',on:true,bri:48,seg:[{id:0,fx:38,pal:50}]},'2':{n:'Spectrum',on:true,bri:80,seg:[{id:0,fx:9,pal:11}]}};
let info={name:'Office',ver:'16.0.1',vid:2610100,arch:'ESP32-C3',simulated:true,ip:'127.0.0.1',mac:'000000000000',freeheap:107000,uptime:3600,wifi:{signal:98},leds:{count:939,fps:42,lc:7,matrix:{w:32,h:20}},canvas:{physicalCount:299}};
let offline=false,reject=false,drop=false,requests=[];const clients=new Set();
function payload(bytes,opcode=1){const length=bytes.length;if(length<126)return Buffer.concat([Buffer.from([0x80|opcode,length]),bytes]);const prefix=Buffer.alloc(4);prefix[0]=0x80|opcode;prefix[1]=126;prefix.writeUInt16BE(length,2);return Buffer.concat([prefix,bytes]);}
function broadcast(){for(const socket of clients)if(!socket.destroyed)socket.write(payload(Buffer.from(JSON.stringify({state,info}))));}
function json(response,value,status=200){response.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});response.end(JSON.stringify(value));}
const settingsMap={wifi:'settings_wifi.htm',leds:'settings_leds.htm',ui:'settings_ui.htm',sync:'settings_sync.htm',time:'settings_time.htm',sec:'settings_sec.htm',um:'settings_um.htm','2D':'settings_2D.htm',pins:'settings_pininfo.htm'};
const server=http.createServer(async(request,response)=>{
	const url=new URL(request.url,'http://localhost'),pathname=url.pathname;
	if(pathname==='/__sim'){if(request.method==='POST'){let raw='';for await(const chunk of request)raw+=chunk;const command=JSON.parse(raw);if('offline'in command)offline=command.offline;if('reject'in command)reject=command.reject;if('drop'in command)drop=command.drop;if(command.state)Object.assign(state,command.state);if(command.info)Object.assign(info,command.info);if(command.clear)requests=[];if(command.disconnect)for(const socket of clients)socket.destroy();broadcast();}json(response,{state,info,presets,requests,offline,reject,drop});return;}
	if(offline&&pathname.startsWith('/json')){json(response,{error:'simulated offline'},503);return;}
	if(request.method==='POST'){
		let raw='';for await(const chunk of request)raw+=chunk;
		if(pathname==='/json/state'){const command=JSON.parse(raw);requests.push({path:pathname,body:command});if(reject){json(response,{error:9},400);return;}if(!drop){
			if(command.psave){const saved=command.o?structuredClone(command):structuredClone(state);delete saved.psave;delete saved.o;presets[command.psave]={...saved,n:command.n,ql:command.ql};}
			else if(command.pdel)delete presets[command.pdel];
			else{const applied=command.ps?presets[command.ps]||{}:command;
				for(const [key,value] of Object.entries(applied)){if(key==='seg'){for(const segment of value){let found=state.seg.find(s=>s.id===segment.id);if(!found){found=makeSegment(segment.id,'',0,1);state.seg.push(found);}Object.assign(found,segment);}state.seg=state.seg.filter(s=>s.stop!==0);}
				else if(key==='canvas'){const descriptors=structuredClone(state.canvas.strips);Object.assign(state.canvas,value,{pending:false,error:0});const offset=value.enabled?value.width*value.height:0;state.canvas.strips=descriptors.map((p,i)=>({...p,...value.strips?.find(s=>s.pin===p.pin),segment:value.enabled?i+1:i}));if(value.enabled){state.seg[0].stop=value.width;state.seg[0].stopY=value.height;info.leds.matrix={w:value.width,h:value.height};}info.leds.count=299+offset;}
				else if(['nl','udpn'].includes(key))Object.assign(state[key],value);else if(['on','bri','transition','lor','mainseg'].includes(key))state[key]=value;else if(key==='playlist')state.pl=value.ps?.length?250:-1;
				}if(command.ps)state.ps=command.ps;
			}broadcast();}
			json(response,state);return;
		}
		if(pathname.startsWith('/settings/')){requests.push({path:pathname,form:raw});response.writeHead(200,{'Content-Type':'text/html'});response.end('<!doctype html><html><head><title>Simulator</title></head><body><h2>Simulated settings saved</h2><p>No hardware was changed.</p></body></html>');return;}
		json(response,{error:'Unsupported simulated operation'},501);return;
	}
	if(pathname==='/json'){json(response,{state,info});return;}
	if(pathname==='/json/state'){json(response,state);return;}
	if(pathname==='/json/info'){json(response,info);return;}
	if(pathname==='/json/effects'){json(response,effects);return;}
	if(pathname==='/json/fxdata'){json(response,fxdata);return;}
	if(pathname==='/json/palettes'){json(response,references.palettes.map(p=>p.name));return;}
	if(pathname==='/json/palx'){const page=Number(url.searchParams.get('page')||0);json(response,{m:Math.floor(references.palettes.length/8),p:Object.fromEntries(references.palettes.slice(page*8,page*8+8).map(p=>[p.id,p.stops]))});return;}
	if(pathname==='/presets.json'){json(response,presets);return;}
	if(pathname==='/json/pins'){json(response,{pins:[]});return;}
	if(pathname==='/settings/s.js'){response.writeHead(200,{'Content-Type':'text/javascript'});response.end('function GetV(){document.max_gpio=22;document.rsvd=[];document.ro_gpio=[];document.touch=[];document.adc=[];document.um_p=[];if(document.Sf&&document.Sf.DS)document.Sf.DS.value="Office Simulator";}');return;}
	let file;if(pathname==='/'&&url.searchParams.has('native'))file='index.htm';else if(pathname==='/'||pathname==='/control')file='control.htm';else if(pathname==='/update')file='update.htm';else if(pathname==='/settings')file='settings.htm';else if(settingsMap[pathname.split('/')[2]])file=settingsMap[pathname.split('/')[2]];else if(pathname==='/cpal.htm')file='cpal/cpal.htm';else if(pathname==='/edit')file='edit.htm';else if(pathname.startsWith('/settings/'))file=path.basename(pathname);else file=pathname.slice(1);
	const target=path.resolve(data,file);if(!target.startsWith(data+path.sep)||!fs.existsSync(target)||!fs.statSync(target).isFile()){response.writeHead(404);response.end('Not found in simulator');return;}
	response.writeHead(200,{'Content-Type':({'.htm':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json'})[path.extname(file)]||'application/octet-stream'});response.end(fs.readFileSync(target));
});
server.on('upgrade',(request,socket)=>{if(new URL(request.url,'http://localhost').pathname!=='/ws'||offline){socket.destroy();return;}const accept=crypto.createHash('sha1').update(request.headers['sec-websocket-key']+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');clients.add(socket);socket.on('error',()=>{});socket.on('close',()=>clients.delete(socket));socket.on('data',bytes=>{if((bytes[0]&15)===8)socket.end();});socket.write(payload(Buffer.from(JSON.stringify({state,info}))));});
setInterval(()=>{if(offline)return;const width=info.leds.matrix?.w||32,height=info.leds.matrix?.h||20,frame=Buffer.alloc(4+width*height*3);frame.set([76,2,width,height]);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const phase=x/width+y/height+Date.now()/8000;for(let c=0;c<3;c++)frame[4+(y*width+x)*3+c]=state.on?Math.round((Math.sin((phase+c/3)*Math.PI*2)+1)*state.bri/2):0;}for(const socket of clients)if(!socket.destroyed)socket.write(payload(frame,2));},100);
server.listen(8096,'127.0.0.1',()=>console.log('WLED simulator: http://localhost:8096/control (no hardware connection)'));
// AI: end
