// AI: below section was generated by an AI
// Serve the new UI locally; forward native WLED requests through an explicit loopback tunnel.
import http from 'node:http';
import net from 'node:net';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const devicePort=Number(process.argv[2]);
if(!Number.isInteger(devicePort)||devicePort<1||devicePort>65535)throw new Error('Pass the loopback port of an established device tunnel');
const data=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../wled00/data');
const assets={'/control':'control.htm','/control.htm':'control.htm','/control.css':'control.css','/control.js':'control.js','/control-previews.js':'control-previews.js'};
const server=http.createServer((request,response)=>{
	const file=assets[new URL(request.url,'http://localhost').pathname];
	if(file&&request.method==='GET'){response.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html','Cache-Control':'no-store'});response.end(fs.readFileSync(path.join(data,file)));return;}
	const upstream=http.request({hostname:'127.0.0.1',port:devicePort,path:request.url,method:request.method,headers:{...request.headers,host:'127.0.0.1:'+devicePort}},result=>{response.writeHead(result.statusCode,result.headers);result.pipe(response);});
	upstream.setTimeout(10000,()=>upstream.destroy(new Error('Controller timeout')));
	upstream.on('error',()=>{if(!response.headersSent)response.writeHead(502,{'Content-Type':'application/json'});response.end('{"error":"Controller tunnel unavailable"}');});request.pipe(upstream);
});
server.on('upgrade',(request,socket,head)=>{const upstream=net.connect(devicePort,'127.0.0.1',()=>{const headers={...request.headers,host:'127.0.0.1:'+devicePort};upstream.write(`${request.method} ${request.url} HTTP/${request.httpVersion}\r\n`+Object.entries(headers).map(([key,value])=>`${key}: ${value}\r\n`).join('')+'\r\n');if(head.length)upstream.write(head);socket.pipe(upstream);upstream.pipe(socket);});socket.on('error',()=>upstream.destroy());upstream.on('error',()=>socket.destroy());socket.on('close',()=>upstream.destroy());});
server.listen(8097,'127.0.0.1',()=>console.log('Local WLED UI with LIVE device controls: http://localhost:8097/control'));
// AI: end
