// AI: below section was generated by an AI.
// Connect a short-lived official MCP client to the existing local Agentation server.
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { fileURLToPath } from 'node:url';

const client = new Client({ name: 'wled-canvas-review', version: '1.0.0' });
const transport = new StdioClientTransport({
	command: process.execPath,
	args: [fileURLToPath(new URL('node_modules/agentation-mcp/dist/cli.js', import.meta.url)),
		'server', '--mcp-only', '--http-url', 'http://localhost:4747'],
	stderr: 'inherit'
});
await client.connect(transport);
try {
	const result = process.argv[2] === 'list'
		? await client.listTools()
		: await client.callTool({ name: process.argv[2], arguments: JSON.parse(process.argv[3] || '{}') });
	console.log(JSON.stringify(result));
} finally {
	await client.close();
}
// AI: end
