// AI: below section was generated by an AI.
// Dev-only toolbar, isolated from the WLED build and controller.
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

process.env.AGENTATION_STORE = 'memory';
process.env.AGENTATION_CORS_ORIGINS = 'http://localhost:8095,http://127.0.0.1:8095';
const { startHttpServer } = await import('agentation-mcp');
startHttpServer(4747);

const bundle = await build({
	entryPoints: [fileURLToPath(new URL('browser-entry.jsx', import.meta.url))],
	bundle: true, write: false, format: 'iife', minify: true,
	define: { 'process.env.NODE_ENV': '"development"' }
});
const files = new Set(['wled-ui-options-prototype.html', 'wled-ui-prototype.html']);

// Serve only prototype pages and the in-memory toolbar bundle on loopback.
const server = createServer(async (request, response) => {
	const path = new URL(request.url, 'http://localhost:8095').pathname;
	response.setHeader('Cache-Control', 'no-store');
	if (path === '/agentation.js') {
		response.writeHead(200, { 'Content-Type': 'text/javascript' });
		response.end(bundle.outputFiles[0].text);
		return;
	}
	const name = path === '/' ? 'wled-ui-options-prototype.html' : path.slice(1);
	if (!files.has(name)) { response.writeHead(404); response.end('Not found'); return; }
	const source = await readFile(new URL('../' + name, import.meta.url), 'utf8');
	const end = source.lastIndexOf('</body>');
	response.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
	response.end(source.slice(0, end) + '<script src="/agentation.js"></script>' + source.slice(end));
});
server.listen(8095, '127.0.0.1', () => {
	console.log('Local Agentation review: http://localhost:8095/?variant=1');
});
// AI: end
